---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse-operator.clickhouseServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse-operator.labels" . | nindent 4 }}
  {{- with .Values.clickhouse.service.serviceLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.clickhouse.service.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.clickhouse.service.type }}
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP
    - name: tcp
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "clickhouse-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: clickhouse
