{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clickhouse-compute.fullname" . }}-data
  labels:
    {{- include "clickhouse-compute.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.keepPVC }}
    "helm.sh/resource-policy": keep
    {{- end }}
    {{- with .Values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.dataSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clickhouse-compute.fullname" . }}-logs
  labels:
    {{- include "clickhouse-compute.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.keepPVC }}
    "helm.sh/resource-policy": keep
    {{- end }}
    {{- with .Values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.logSize }}
{{- end }}