{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "clickhouse-compute.fullname" . }}
  labels:
    {{- include "clickhouse-compute.labels" . | nindent 4 }}
rules:
  {{- if .Values.rbac.rules }}
  {{- toYaml .Values.rbac.rules | nindent 2 }}
  {{- else }}
  []
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "clickhouse-compute.fullname" . }}
  labels:
    {{- include "clickhouse-compute.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "clickhouse-compute.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "clickhouse-compute.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
