---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse-compute.fullname" . }}-secrets
  labels:
    {{- include "clickhouse-compute.labels" . | nindent 4 }}
type: Opaque
data:
  appUserPassword: {{ .Values.config.users.appUserPassword | toString | b64enc }}