apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse-compute.fullname" . }}-secrets
  labels:
    {{- include "clickhouse-compute.labels" . | nindent 4 }}
type: Opaque
data:
  accessKey: {{ .Values.storage.s3.accessKey | b64enc | quote }}
  secretKey: {{ .Values.storage.s3.secretKey | b64enc | quote }}
