apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse-compute.fullname" . }}
  labels:
    {{- include "clickhouse-compute.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.tcpPort }}
      targetPort: {{ .Values.service.tcpPort }}
      protocol: TCP
      name: tcp
  selector:
    {{- include "clickhouse-compute.selectorLabels" . | nindent 4 }}
