---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse-compute.fullname" . }}-clickhouse
  labels:
    {{- include "clickhouse-compute.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      name: http
    - port: {{ .Values.service.tcpPort }}
      targetPort: {{ .Values.service.tcpPort }}
      name: native
    {{- if .Values.prometheus.enabled }}
    - port: {{ .Values.prometheus.port }}
      targetPort: {{ .Values.prometheus.port }}
      name: prometheus
    {{- end }}
  selector:
    {{- include "clickhouse-compute.selectorLabels" . | nindent 4 }}
    app: clickhouse