{{ if .Values.storage.s3.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  {{- with .Values.storage.s3.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fstype: ext4
  encrypted: true
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{- end }}