apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-metrics-query-service.fullname" . }}-secrets
  labels:
    {{- include "product-metrics-query-service.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data: {}
  # Add secret data here

