apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parquet-converter.fullname" . }}-secrets
  labels:
    {{- include "parquet-converter.labels" . | nindent 4 }}
type: Opaque
data:
  # Add secret data here
