{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "product-metrics.fullname" . }}
  labels:
    {{- include "product-metrics.labels" . | nindent 4 }}
rules:
  {{- if .Values.rbac.rules }}
  {{- toYaml .Values.rbac.rules | nindent 2 }}
  {{- else }}
  []
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "product-metrics.fullname" . }}
  labels:
    {{- include "product-metrics.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "product-metrics.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "product-metrics.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
