apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-metrics.fullname" . }}-secrets
  labels:
    {{- include "product-metrics.labels" . | nindent 4 }}
type: Opaque
data: {}
  # Add secret data here

