apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pmqs.fullname" . }}-secrets
  labels:
    {{- include "pmqs.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data: {}
  # Add secret data here

